const MIXER_CHAT_URL = 'https://mixer.com/embed/chat';
const MIXER_PLAYER_URL = 'https://mixer.com/embed/player';

const CHAT_DEFAULT_HEIGHT = 500;
const CHAT_DEFAULT_WIDTH = 350;
const PLAYER_DEFAULT_HEIGHT = 480;
const PLAYER_DEFAULT_WIDTH = 940;

export {
  MIXER_CHAT_URL,
  MIXER_PLAYER_URL,
  CHAT_DEFAULT_WIDTH,
  CHAT_DEFAULT_HEIGHT,
  PLAYER_DEFAULT_HEIGHT,
  PLAYER_DEFAULT_WIDTH
};
